image: php:8.1

pipelines:
  default:
    - step:
        name: 'Composer Install'
        caches:
          - composer
        script:
          - apt update && apt install -y curl libzip-dev unzip zip # Plus all other dependencies..
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          # Install more dependencies here
          - composer install --no-interaction --no-scripts
          # Run the tests etc..
        artifacts:
          - vendor/**
    - parallel:
        - step:
            name: 'Analysis: PHPstan'
            script:
              - vendor/bin/phpstan analyse --no-progress --level=7 --memory-limit=-1 src
        - step:
            name: 'Test: PHPUnit'
            script:
              - vendor/bin/phpunit tests